"""Form 26AS / AIS extraction.

26AS is generated by TRACES from a fixed template, so unlike a bank statement
its structure is predictable: numbered parts, each introduced by a caption, each
holding a table of deductor rows. The work is therefore mostly in deciding which
part a given table belongs to and in coping with the two-row-per-entry layout
TRACES uses, where the deductor's name and TAN sit on one row and the
transaction details on the rows beneath.

AIS uses a near-identical table shape and usually parses, but 26AS is the format
this is tested against — the output sheet says so.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from decimal import Decimal
from typing import Optional, Sequence

from textutil import TAN_RE, normalise_space, parse_amount, parse_date

PART_CAPTIONS = (
    ("PART A", re.compile(r"part\s*-?\s*a\b(?!\d)", re.IGNORECASE), "Part A - TDS"),
    ("PART A1", re.compile(r"part\s*-?\s*a1\b", re.IGNORECASE), "Part A1 - 15G 15H"),
    ("PART A2", re.compile(r"part\s*-?\s*a2\b", re.IGNORECASE), "Part A2 - TDS on property"),
    ("PART B", re.compile(r"part\s*-?\s*b\b(?!\d)", re.IGNORECASE), "Part B - TCS"),
)

ENTRY_HEADER_HINTS = ("deductor", "collector", "tan", "section", "amount paid", "tax deducted")


@dataclass
class TdsEntry:
    deductor: str = ""
    tan: str = ""
    section: str = ""
    transaction_date: Optional[object] = None
    booking_date: Optional[object] = None
    amount_paid: Optional[Decimal] = None
    tax_deducted: Optional[Decimal] = None
    tds_deposited: Optional[Decimal] = None


@dataclass
class Part:
    title: str
    entries: list[TdsEntry] = field(default_factory=list)


@dataclass
class Form26AS:
    parts: list[Part] = field(default_factory=list)
    total_tax_deducted: Optional[Decimal] = None
    warnings: list[str] = field(default_factory=list)
    confidence: float = 0.0


def _looks_like_entry_header(row: Sequence[Optional[str]]) -> bool:
    joined = " ".join(normalise_space(cell).lower() for cell in row if cell)
    return sum(1 for hint in ENTRY_HEADER_HINTS if hint in joined) >= 2


def _column_index(header: Sequence[Optional[str]], *needles: str) -> Optional[int]:
    for index, cell in enumerate(header):
        text = normalise_space(cell).lower()
        if any(needle in text for needle in needles):
            return index
    return None


def _part_for_page(page_text: str, current: Optional[str]) -> Optional[str]:
    """Which part a page belongs to, carrying the previous one across page breaks."""
    for _, pattern, title in PART_CAPTIONS:
        if pattern.search(page_text):
            return title
    return current


def _rows_to_entries(table: Sequence[Sequence[Optional[str]]]) -> list[TdsEntry]:
    header = table[0]
    index = {
        "deductor": _column_index(header, "deductor", "collector", "name of"),
        "tan": _column_index(header, "tan"),
        "section": _column_index(header, "section"),
        "transaction_date": _column_index(header, "transaction date", "date of transaction"),
        "booking_date": _column_index(header, "booking", "date of booking"),
        "amount_paid": _column_index(header, "amount paid", "amount credited", "amount"),
        "tax_deducted": _column_index(header, "tax deducted", "tds deducted"),
        "tds_deposited": _column_index(header, "deposited", "tds deposited"),
    }

    entries: list[TdsEntry] = []
    # TRACES prints the deductor once and then several transaction rows beneath
    # it, so an empty deductor cell means "same deductor as above".
    last_deductor = ""
    last_tan = ""

    for row in table[1:]:
        cell = lambda key: (  # noqa: E731
            normalise_space(row[index[key]])
            if index[key] is not None and index[key] < len(row)
            else ""
        )

        deductor = cell("deductor") or last_deductor
        tan = cell("tan") or last_tan
        if not tan:
            match = TAN_RE.search(" ".join(normalise_space(c) for c in row if c))
            tan = match.group(0) if match else last_tan

        amount = parse_amount(cell("amount_paid"))
        tax = parse_amount(cell("tax_deducted"))
        if amount is None and tax is None:
            # A pure deductor heading row: remember it and move on.
            if cell("deductor"):
                last_deductor, last_tan = deductor, tan
            continue

        entries.append(
            TdsEntry(
                deductor=deductor,
                tan=tan,
                section=cell("section"),
                transaction_date=parse_date(cell("transaction_date")),
                booking_date=parse_date(cell("booking_date")),
                amount_paid=amount,
                tax_deducted=tax,
                tds_deposited=parse_amount(cell("tds_deposited")),
            )
        )
        last_deductor, last_tan = deductor, tan

    return entries


def parse(pdf) -> Form26AS:
    statement = Form26AS()
    by_title: dict[str, Part] = {}
    current_title: Optional[str] = None

    for page in pdf.pages:
        current_title = _part_for_page(page.extract_text() or "", current_title)
        title = current_title or "Part A - TDS"

        for table in page.extract_tables() or []:
            if not table or not _looks_like_entry_header(table[0]):
                continue
            entries = _rows_to_entries(table)
            if not entries:
                continue
            part = by_title.setdefault(title, Part(title=title))
            part.entries.extend(entries)

    statement.parts = list(by_title.values())

    if not statement.parts:
        statement.warnings.append(
            "No TDS tables were found. If this file came straight from TRACES it is password "
            "protected — unlock it first with your date of birth in DDMMYYYY form."
        )
    else:
        statement.total_tax_deducted = sum(
            (entry.tax_deducted or Decimal(0)) for part in statement.parts for entry in part.entries
        )

    entries = [entry for part in statement.parts for entry in part.entries]
    if entries:
        complete = sum(1 for entry in entries if entry.tan and entry.tax_deducted is not None)
        statement.confidence = round(complete / len(entries), 3)
        if statement.confidence < 0.9:
            statement.warnings.append(
                "Some entries are missing a TAN or a tax figure. Reconcile against the income "
                "tax portal before relying on this sheet."
            )

    return statement
